// <auto-generated />
namespace VideoLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ApplyDataAnnotationsOnGenreAndMovieTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ApplyDataAnnotationsOnGenreAndMovieTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201808151346364_ApplyDataAnnotationsOnGenreAndMovieTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
